export const AppActionType = {
    FETCH_SHIPMENTS_REQUEST: "FETCH_SHIPMENTS_REQUEST",
    FETCH_SHIPMENTS_SUCCESS: "FETCH_SHIPMENTS_SUCCESS",
    FETCH_SHIPMENTS_FAILURE: "FETCH_SHIPMENTS_FAILURE",
    LOADED_FROM_FILE:"LOADED_FROM_FILE",
    DELETE_SHIPMENT: "DELETE_SHIPMENT",
    ADD_SHIPMENT: "ADD_SHIPMENT"
};



